name: Papillon Hair Designs
favicon: null
layout_spectrum: 0.26552
title: Papillon Hair Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbe153'
    - '#3d1314'
    - '#8f7b50'
    - '#d66e2c'
    - '#f5c221'
  brandStrength: 1
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
